### PR TITLE
Demo of MediatR for a Command and Query

### PR DESCRIPTION
**Pull request by dcomartin**
Here you go sir... I added a idempotent PUT.  You can get rid of it and turn the call into a POST if that makes it more straight forward.

### CODE REVIEW

**Comment by dcomartin** [comment]
I haven't blogged about this yet, but wanted to get you something since you were curious.

**Comment by jchannon** [comment]
Great. I'll take a look tomorrow

**Comment by jchannon** [comment]
I will look at this I'm just trying to get a hand rolled version spiked out and its taking longer than i thought :smile:

**Comment by jchannon** [comment]
:+1: :trophy:

**Pull request merged**
